name: hotly_app
description: AI 기반 핫플레이스 아카이빙 앱
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.3.0
  flutter: ^3.19.0

# ========== Core Dependencies ==========
dependencies:
  flutter:
    sdk: flutter

  # 상태 관리
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.3
  get_it: ^7.6.7

  # 네트워킹
  dio: ^5.4.1
  dio_smart_retry: ^6.0.0
  connectivity_plus: ^5.0.2
  pretty_dio_logger: ^1.3.1

  # 데이터 모델 및 직렬화
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # 로컬 스토리지
  sqflite: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  path_provider: ^2.1.2

  # 라우팅
  go_router: ^13.2.0

  # Firebase - Authentication 및 Backend Services
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.3  # Firebase Authentication 추가
  firebase_messaging: ^15.1.5
  firebase_analytics: ^11.3.5
  firebase_crashlytics: ^4.1.5
  firebase_performance: ^0.10.0+10
  flutter_local_notifications: ^16.3.2

  # 소셜 로그인
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^5.0.0
  kakao_flutter_sdk_user: ^1.9.0  # Kakao 로그인 (호환성을 위해 다운그레이드)

  # UI/UX
  flutter_animate: ^4.5.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  infinite_scroll_pagination: ^4.0.0
  pull_to_refresh: ^2.0.0
  flutter_staggered_grid_view: ^0.7.0
  smooth_page_indicator: ^1.1.0

  # 지도 및 위치
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  kakao_map_sdk: ^1.2.0  # Kakao Maps SDK with iOS/Android/Web support

  # 이미지
  image_picker: ^1.0.7
  flutter_image_compress: ^2.1.0
  photo_view: ^0.14.0

  # 유틸리티
  intl: ^0.19.0
  uuid: ^4.3.3
  url_launcher: ^6.2.4
  share_plus: ^7.2.2
  uni_links: ^0.5.1
  receive_sharing_intent: ^1.8.0
  permission_handler: ^11.2.0
  package_info_plus: ^8.0.0
  device_info_plus: ^9.1.2

  # 환경 변수
  flutter_dotenv: ^5.1.0

  # 로깅
  logger: ^2.0.2+1

  # 기타
  equatable: ^2.0.5
  dartz: ^0.10.1
  google_fonts: ^6.1.0

# ========== Dev Dependencies ==========
dev_dependencies:
  flutter_test:
    sdk: flutter

  # 코드 생성
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9
  hive_generator: ^2.0.1

  # 테스팅
  mocktail: ^1.0.3
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

  # Lint 및 분석
  flutter_lints: ^3.0.1
  very_good_analysis: ^5.1.0
  custom_lint: ^0.6.7
  riverpod_lint: ^2.3.13

  # 유틸리티
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

# ========== Flutter 설정 ==========
flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/images/logo/
    - assets/images/onboarding/
    - assets/images/placeholder/
    - assets/icons/
    - assets/animations/
    - .env.dev
    - .env.staging
    - .env.prod
    - assets/kakao_map.html

  # Fonts
  fonts: []
  #     - family: Pretendard
  #       fonts:
  #         - asset: assets/fonts/Pretendard/Pretendard-Regular.otf
  #           weight: 400
  #         - asset: assets/fonts/Pretendard/Pretendard-Medium.otf
  #           weight: 500
  #         - asset: assets/fonts/Pretendard/Pretendard-SemiBold.otf
  #           weight: 600
  #         - asset: assets/fonts/Pretendard/Pretendard-Bold.otf
  #           weight: 700

# ========== Flutter Launcher Icons 설정 ==========
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo/app_icon_foreground.png"

# ========== Flutter Native Splash 설정 ==========
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo/splash_logo.png
  android: true
  ios: true
  android_12:
    color: "#FFFFFF"
    image: assets/images/logo/splash_logo.png
